/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Usuario
 */
public class Administrador extends javax.swing.JFrame {

    Aerolineas aerolineas;
            
    public Administrador() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DesktopAdministrador = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        JMB_MenuAdministrador = new javax.swing.JMenuBar();
        JMB_aerolineas = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bienvenido Administrador");

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Bienvenido Administrador.");

        DesktopAdministrador.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout DesktopAdministradorLayout = new javax.swing.GroupLayout(DesktopAdministrador);
        DesktopAdministrador.setLayout(DesktopAdministradorLayout);
        DesktopAdministradorLayout.setHorizontalGroup(
            DesktopAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesktopAdministradorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(272, Short.MAX_VALUE))
        );
        DesktopAdministradorLayout.setVerticalGroup(
            DesktopAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesktopAdministradorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(379, Short.MAX_VALUE))
        );

        JMB_aerolineas.setText("Aerolíneas");
        JMB_aerolineas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JMB_aerolineasMouseClicked(evt);
            }
        });
        JMB_aerolineas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMB_aerolineasActionPerformed(evt);
            }
        });
        JMB_MenuAdministrador.add(JMB_aerolineas);

        jMenu2.setText("Edit");
        JMB_MenuAdministrador.add(jMenu2);

        setJMenuBar(JMB_MenuAdministrador);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopAdministrador)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopAdministrador, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMB_aerolineasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMB_aerolineasActionPerformed
         
    }//GEN-LAST:event_JMB_aerolineasActionPerformed

    private void JMB_aerolineasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JMB_aerolineasMouseClicked
        aerolineas = new Aerolineas();
        int x = (DesktopAdministrador.getWidth() / 2) - aerolineas.getWidth() / 2;
        int y = (DesktopAdministrador.getHeight() / 2) - aerolineas.getHeight() / 2;
        DesktopAdministrador.add(aerolineas);
        aerolineas.setLocation(x, y);
        aerolineas.show();
    }//GEN-LAST:event_JMB_aerolineasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopAdministrador;
    private javax.swing.JMenuBar JMB_MenuAdministrador;
    private javax.swing.JMenu JMB_aerolineas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    // End of variables declaration//GEN-END:variables
}
