/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Usuario
 */
public class Aerolineas extends javax.swing.JInternalFrame {

    /**
     * Creates new form Aerolineas
     */
    public Aerolineas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JL_fondo = new javax.swing.JLabel();
        JMB_aerolineas = new javax.swing.JMenuBar();
        JM_agregarAerolinea = new javax.swing.JMenu();
        JM_modificarAerolinea = new javax.swing.JMenu();
        JM_suprimirAerolinea = new javax.swing.JMenu();
        JM_consultarAerolinea = new javax.swing.JMenu();
        JM_imprimir = new javax.swing.JMenu();

        setClosable(true);
        setIconifiable(true);
        setTitle("Aerolineas");

        JL_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoAdminis.jpg"))); // NOI18N

        JM_agregarAerolinea.setText("Agregar");
        JMB_aerolineas.add(JM_agregarAerolinea);

        JM_modificarAerolinea.setText("Modificar");
        JMB_aerolineas.add(JM_modificarAerolinea);

        JM_suprimirAerolinea.setText("Suprimir");
        JMB_aerolineas.add(JM_suprimirAerolinea);

        JM_consultarAerolinea.setText("Consultar");
        JMB_aerolineas.add(JM_consultarAerolinea);

        JM_imprimir.setText("Imprimir");
        JMB_aerolineas.add(JM_imprimir);

        setJMenuBar(JMB_aerolineas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JL_fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JL_fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JL_fondo;
    private javax.swing.JMenuBar JMB_aerolineas;
    private javax.swing.JMenu JM_agregarAerolinea;
    private javax.swing.JMenu JM_consultarAerolinea;
    private javax.swing.JMenu JM_imprimir;
    private javax.swing.JMenu JM_modificarAerolinea;
    private javax.swing.JMenu JM_suprimirAerolinea;
    // End of variables declaration//GEN-END:variables
}
