/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Cursor;

/**
 *
 * @author Usuario
 */
public class LoginCombo extends javax.swing.JFrame {

    Administrador JFAdministrador;
    String opcion = "";

    public LoginCombo() {
        initComponents();
        JL_Id.setVisible(false);
        JL_ContraseñaAdministrador.setVisible(false);
        JTF_getId.setVisible(false);
        JPF_Contraseña.setVisible(false);
        JL_Correo.setVisible(false);
        JTF_Correo.setVisible(false);
        JL_NombreUsuario.setVisible(false);
        JTF_getNombreUsuario.setVisible(false);
        JL_Registrarse.setVisible(false);
        JB_ingresarUsuario.setVisible(false);
        JB_ingresarAdm.setVisible(false);
        JL_cuentaNueva.setVisible(false);
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JL_imagen = new javax.swing.JLabel();
        JL_tipoUsuario = new javax.swing.JLabel();
        JCB_Menu = new javax.swing.JComboBox<>();
        JL_cuentaNueva = new javax.swing.JLabel();
        JL_Id = new javax.swing.JLabel();
        JTF_getId = new javax.swing.JTextField();
        JL_ContraseñaAdministrador = new javax.swing.JLabel();
        JPF_Contraseña = new javax.swing.JPasswordField();
        JL_NombreUsuario = new javax.swing.JLabel();
        JTF_getNombreUsuario = new javax.swing.JTextField();
        JL_Correo = new javax.swing.JLabel();
        JTF_Correo = new javax.swing.JTextField();
        JB_ingresarUsuario = new javax.swing.JButton();
        JB_ingresarAdm = new javax.swing.JButton();
        JL_Registrarse = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bienvenido");

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        JL_imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/psd-world-map-icon_0.png"))); // NOI18N

        JL_tipoUsuario.setText("Tipo de usuario:");

        JCB_Menu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elige Opcion", "Administrador ", "Usuario" }));
        JCB_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCB_MenuActionPerformed(evt);
            }
        });

        JL_cuentaNueva.setText("Cree su cuenta");

        JL_Id.setText("Nombre de usuario:");

        setVisible(false);

        JL_ContraseñaAdministrador.setText("Contraseña:");

        JL_NombreUsuario.setText("Nombre:");

        JL_Correo.setText("Correo");

        JB_ingresarUsuario.setText("Ingresar");
        JB_ingresarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_ingresarUsuarioActionPerformed(evt);
            }
        });

        JB_ingresarAdm.setText("Ingresar");
        JB_ingresarAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_ingresarAdmActionPerformed(evt);
            }
        });

        JL_Registrarse.setForeground(new java.awt.Color(0, 51, 255));
        JL_Registrarse.setText("Registrarse");
        JL_Registrarse.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                JL_RegistrarseMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                JL_RegistrarseMouseMoved(evt);
            }
        });
        JL_Registrarse.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JL_RegistrarseFocusLost(evt);
            }
        });
        JL_Registrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JL_RegistrarseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(JL_imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(JB_ingresarUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(JB_ingresarAdm)
                        .addGap(503, 503, 503))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(JL_tipoUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JCB_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(511, 511, 511))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(JL_cuentaNueva))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(JL_Id)
                                    .addComponent(JL_ContraseñaAdministrador)
                                    .addComponent(JL_NombreUsuario)
                                    .addComponent(JL_Correo)
                                    .addComponent(JL_Registrarse))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JPF_Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JTF_getId, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JTF_getNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JTF_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(526, 526, 526))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JL_tipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JCB_Menu))
                        .addGap(18, 18, 18)
                        .addComponent(JL_cuentaNueva)
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JL_Id)
                            .addComponent(JTF_getId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JL_ContraseñaAdministrador)
                            .addComponent(JPF_Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JL_NombreUsuario)
                            .addComponent(JTF_getNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JL_Correo)
                            .addComponent(JTF_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(JL_imagen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_ingresarUsuario)
                    .addComponent(JB_ingresarAdm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JL_Registrarse)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JL_RegistrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL_RegistrarseMouseClicked

        JL_ContraseñaAdministrador.setVisible(false);
        JPF_Contraseña.setVisible(false);
        JTF_getId.setVisible(true);
        JL_Id.setVisible(true);
        JL_Correo.setVisible(true);
        JTF_Correo.setVisible(true);
        JL_NombreUsuario.setVisible(true);
        JTF_getNombreUsuario.setVisible(true);
        JL_Registrarse.setVisible(false);
        JB_ingresarUsuario.setVisible(true);
        JB_ingresarAdm.setVisible(false);
        JL_cuentaNueva.setVisible(true);
    }//GEN-LAST:event_JL_RegistrarseMouseClicked

    private void JL_RegistrarseFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JL_RegistrarseFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_JL_RegistrarseFocusLost

    private void JL_RegistrarseMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL_RegistrarseMouseMoved
        // TODO add your handling code here:
        Cursor cursor = new Cursor(HAND_CURSOR);
        JL_Registrarse.setCursor(cursor);
    }//GEN-LAST:event_JL_RegistrarseMouseMoved

    private void JL_RegistrarseMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL_RegistrarseMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_JL_RegistrarseMouseDragged

    private void JB_ingresarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_ingresarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JB_ingresarUsuarioActionPerformed

    private void JCB_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCB_MenuActionPerformed
        getOpcion(JCB_Menu.getSelectedItem().toString());
        if (opcion.equalsIgnoreCase("Usuario")) {
            JL_ContraseñaAdministrador.setVisible(false);
            JTF_getId.setVisible(false);
            JPF_Contraseña.setVisible(false);
            JL_Id.setVisible(true);
            JTF_getId.setVisible(true);
            JL_Correo.setVisible(false);
            JTF_Correo.setVisible(false);
            JL_NombreUsuario.setVisible(false);
            JTF_getNombreUsuario.setVisible(false);
            JL_Registrarse.setVisible(true);
            JB_ingresarUsuario.setVisible(true);
            JB_ingresarAdm.setVisible(false);
            JL_cuentaNueva.setVisible(false);
        } else if (opcion.equalsIgnoreCase("Administrador ")) {
            JL_Id.setVisible(true);
            JL_ContraseñaAdministrador.setVisible(true);
            JTF_getId.setVisible(true);
            JPF_Contraseña.setVisible(true);
            JL_Correo.setVisible(false);
            JTF_Correo.setVisible(false);
            JL_NombreUsuario.setVisible(false);
            JTF_getNombreUsuario.setVisible(false);
            JL_Registrarse.setVisible(false);
            JB_ingresarAdm.setVisible(true);
            JB_ingresarUsuario.setVisible(false);
            JL_cuentaNueva.setVisible(false);

        }
    }//GEN-LAST:event_JCB_MenuActionPerformed

    private void JB_ingresarAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_ingresarAdmActionPerformed
        JFAdministrador = new Administrador();
        JFAdministrador.setVisible(true);
        
        
        
    }//GEN-LAST:event_JB_ingresarAdmActionPerformed
public void getOpcion(String boxOpcion) {
        opcion = boxOpcion;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginCombo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginCombo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginCombo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginCombo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginCombo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_ingresarAdm;
    private javax.swing.JButton JB_ingresarUsuario;
    private javax.swing.JComboBox<String> JCB_Menu;
    private javax.swing.JLabel JL_ContraseñaAdministrador;
    private javax.swing.JLabel JL_Correo;
    private javax.swing.JLabel JL_Id;
    private javax.swing.JLabel JL_NombreUsuario;
    private javax.swing.JLabel JL_Registrarse;
    private javax.swing.JLabel JL_cuentaNueva;
    private javax.swing.JLabel JL_imagen;
    private javax.swing.JLabel JL_tipoUsuario;
    private javax.swing.JPasswordField JPF_Contraseña;
    private javax.swing.JTextField JTF_Correo;
    private javax.swing.JTextField JTF_getId;
    private javax.swing.JTextField JTF_getNombreUsuario;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
