/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Archivos.Archivos;
import dominio.Aerolinea;
import TDA.lista.ListaEnlazada;
import TDA.lista.ListaException;
import java.awt.Dimension;
import java.io.File;
import java.io.Serializable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Logica.TableCellRendererColor;
import Logica.Utilidades;

public class JIF_AgregaAerolinea extends javax.swing.JFrame implements Serializable {

    private DefaultTableModel modelo;
    TableCellRendererColor estado = new TableCellRendererColor(1, 2, 3, 4, -1, -1, -1);

    ListaEnlazada lista;
    Aerolinea aero;
    Archivos a;
    Object arreglo[];
    File f;

    /**
     * Creates new form Aerolinea
     */
    public JIF_AgregaAerolinea() {

        this.setTitle("Aerolíneas");

        initComponents();
        this.setMinimumSize(new Dimension(fondo.getWidth(), fondo.getHeight()));
        this.setResizable(false);
        
        
        lista = new ListaEnlazada();
        f = new File("aerolineas.dat");
        a = new Archivos();

      
        //aparezca en el centro
        this.setLocationRelativeTo(null);
    }

    public void reseteo() {
        for (int i = modelo.getRowCount() - 1; i >= 0; i--) {
            modelo.removeRow(i);
        }

    }

    public void Modifica() throws TDA.lista.ListaException {
        
        ListaEnlazada lista = new ListaEnlazada();
        ListaEnlazada aero = (ListaEnlazada) a.leerArchivo("aerolineas.dat");

        a.escribirArchivo(lista, "aerolineas.dat");

    }

    public void primerAerolinea() throws TDA.lista.ListaException {

        ListaEnlazada lista = new ListaEnlazada();
        if (!JTF_Nombre.getText().equals("") && !JTF_correo.getText().equals("")) {
            if (Utilidades.validaNumero(JTF_Telef.getText())
                    && Utilidades.validaTexto(JTF_Nombre.getText())) {
                lista.insertar(new Aerolinea((short) 0, JTF_Nombre.getText(), JTF_web.getText(), JTF_Telef.getText(), JTF_correo.getText()));
                JTF_Nombre.setText("");
                JTF_web.setText("");
                JTF_correo.setText("");
                JTF_Telef.setText("");
                a.escribirArchivo(lista, "aerolineas.dat");
            }
        }

    }

      public void Agregar() throws TDA.lista.ListaException {
        if(!f.exists()){
            primerAerolinea();
        }else{
            ListaEnlazada lista1 = new  ListaEnlazada();
            ListaEnlazada lista2 = new   ListaEnlazada();
            if(!JTF_Nombre.getText().equals("")&&!JTF_web.getText().equals("")&&!JTF_correo.getText().equals("")&&!JTF_Telef.getText().equals("")){
                //lista2.clear();
             if(Utilidades.validaTexto(JTF_Nombre.getText())&& Utilidades.validaNumero(JTF_Telef.getText())){   
                ListaEnlazada usuario =  (ListaEnlazada) a.leerArchivo("aerolineas.dat");
                for(int i = 1;i<=usuario.getSize();i++){
                    
                    Aerolinea ae = (Aerolinea)usuario.getNodo(i).elemento;
                    lista1.insertar(new Aerolinea((short) i,ae.getNombre(),ae.getSitioWeb(),ae.getTelefono(), ae.getCorreo()));
                }
                lista1.insertar(new Aerolinea ((short)0,JTF_Nombre.getText(),JTF_web.getText(), JTF_Telef.getText(),JTF_correo.getText()));
                JTF_Nombre.setText("");
                JTF_web.setText("");
                JTF_correo.setText("");
                JTF_Telef.setText("");
                a.escribirArchivo(lista1,"aerolineas.dat");
                ListaEnlazada usuario2 =  (ListaEnlazada) a.leerArchivo("aerolineas.dat");
                for(int i = 1;i<=usuario2.getSize();i++){
                    Aerolinea ae = (Aerolinea)usuario2.getNodo(i).elemento;
                    lista2.insertar(new Aerolinea((short) i,ae.getNombre(),ae.getSitioWeb(),ae.getCorreo(), ae.getTelefono()));
                }
                a.escribirArchivo(lista2,"aerolineas.dat");
             }
            }else{
                JOptionPane.showMessageDialog(null,"Lo sentimos hay espacios sin llenar");
            }
        }
    }
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        JB_agregar = new javax.swing.JButton();
        JL_nombre = new javax.swing.JLabel();
        JL_correo = new javax.swing.JLabel();
        JL_web = new javax.swing.JLabel();
        JL_Telefono = new javax.swing.JLabel();
        JTF_Nombre = new javax.swing.JTextField();
        JTF_correo = new javax.swing.JTextField();
        JTF_Telef = new javax.swing.JTextField();
        JTF_web = new javax.swing.JTextField();
        fondo = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        JB_agregar.setBackground(new java.awt.Color(153, 153, 153));
        JB_agregar.setText("Agregar ");
        JB_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_agregarActionPerformed(evt);
            }
        });
        getContentPane().add(JB_agregar);
        JB_agregar.setBounds(160, 380, 110, 23);

        JL_nombre.setBackground(new java.awt.Color(0, 0, 0));
        JL_nombre.setText("Nombre :");
        getContentPane().add(JL_nombre);
        JL_nombre.setBounds(80, 100, 70, 14);

        JL_correo.setText("Correo :");
        getContentPane().add(JL_correo);
        JL_correo.setBounds(80, 220, 50, 14);

        JL_web.setBackground(new java.awt.Color(0, 0, 0));
        JL_web.setText("Sitio Web:");
        getContentPane().add(JL_web);
        JL_web.setBounds(80, 150, 60, 14);

        JL_Telefono.setText("Telefono:");
        getContentPane().add(JL_Telefono);
        JL_Telefono.setBounds(70, 300, 70, 14);

        JTF_Nombre.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(JTF_Nombre);
        JTF_Nombre.setBounds(180, 90, 220, 30);

        JTF_correo.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(JTF_correo);
        JTF_correo.setBounds(180, 220, 230, 30);

        JTF_Telef.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(JTF_Telef);
        JTF_Telef.setBounds(180, 290, 230, 30);

        JTF_web.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(JTF_web);
        JTF_web.setBounds(180, 150, 220, 30);
        getContentPane().add(fondo);
        fondo.setBounds(0, 0, 790, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_agregarActionPerformed
        try {
            Agregar();
//            Aerolinea aerolinea = new Aerolinea();
//            aerolinea.mostrarAerolineas();
//            setVisible(false);
//            aerolinea.setVisible(true);
        } catch (ListaException ex) {
            Logger.getLogger(JIF_AgregaAerolinea.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JB_agregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JIF_AgregaAerolinea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JIF_AgregaAerolinea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JIF_AgregaAerolinea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JIF_AgregaAerolinea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AgregaAerolinea().setVisible(true);
//            }
//        });
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new JIF_AgregaAerolinea().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_agregar;
    private javax.swing.JLabel JL_Telefono;
    private javax.swing.JLabel JL_correo;
    private javax.swing.JLabel JL_nombre;
    private javax.swing.JLabel JL_web;
    private javax.swing.JTextField JTF_Nombre;
    private javax.swing.JTextField JTF_Telef;
    private javax.swing.JTextField JTF_correo;
    private javax.swing.JTextField JTF_web;
    private javax.swing.JLabel fondo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
