/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import TDA.lista.ListaEnlazada;
import TDA.lista.ListaException;
import java.io.IOException;
import java.io.Serializable;
import java.util.logging.Level;
import java.util.logging.Logger;
import dominio.Agencia;
import logica.AgenciaData;

/**
 *
 * @author Arturo
 */
public class JIF_IngresarAgencia extends javax.swing.JInternalFrame implements Serializable {

    AgenciaData agenciaData;
    

    public JIF_IngresarAgencia() {
        
        initComponents();
        try {
            agenciaData = new AgenciaData("agencias.dat");
        } catch (IOException ex) {
            Logger.getLogger(JIF_IngresarAgencia.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_nombre = new javax.swing.JLabel();
        jl_ubicacion = new javax.swing.JLabel();
        jl_telefonos = new javax.swing.JLabel();
        jl_correo = new javax.swing.JLabel();
        jtf_nombre = new javax.swing.JTextField();
        jtf_ubiacion = new javax.swing.JTextField();
        jtf_telefonos = new javax.swing.JTextField();
        jtf_correo = new javax.swing.JTextField();
        jb_agregar = new javax.swing.JButton();

        setClosable(true);

        jl_nombre.setText("Nombre");

        jl_ubicacion.setText("Ubicación");

        jl_telefonos.setText("Teléfonos");

        jl_correo.setText("Correo");

        jtf_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_nombreActionPerformed(evt);
            }
        });

        jtf_ubiacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_ubiacionActionPerformed(evt);
            }
        });

        jb_agregar.setText("Agregar");
        jb_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_agregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_agregar)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jl_telefonos)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jl_nombre)
                                    .addComponent(jl_ubicacion)))
                            .addComponent(jl_correo))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtf_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(jtf_ubiacion)
                            .addComponent(jtf_telefonos)
                            .addComponent(jtf_correo))))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_nombre)
                    .addComponent(jtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_ubicacion)
                    .addComponent(jtf_ubiacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_telefonos)
                    .addComponent(jtf_telefonos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_correo)
                    .addComponent(jtf_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jb_agregar)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_nombreActionPerformed

    private void jtf_ubiacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_ubiacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_ubiacionActionPerformed

    private void jb_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_agregarActionPerformed
        String nombre = (jtf_nombre.getText());
        String ubicacion = (jtf_ubiacion.getText());
        String telefono = (jtf_telefonos.getText());
        ListaEnlazada listaTelefonos = new ListaEnlazada();
        listaTelefonos.insertar(telefono);
        String correo = (jtf_correo.getText());

        ListaEnlazada aerolineas = new ListaEnlazada();
        Agencia a = new Agencia(nombre, ubicacion, listaTelefonos, correo, aerolineas);
        try {
            agenciaData.agregarAgencia(a);
            System.out.println(agenciaData.obtenerTodasLasAgencias().toString());

        } catch (ListaException | IOException ex) {
            Logger.getLogger(JIF_IngresarAgencia.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jb_agregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jb_agregar;
    private javax.swing.JLabel jl_correo;
    private javax.swing.JLabel jl_nombre;
    private javax.swing.JLabel jl_telefonos;
    private javax.swing.JLabel jl_ubicacion;
    private javax.swing.JTextField jtf_correo;
    private javax.swing.JTextField jtf_nombre;
    private javax.swing.JTextField jtf_telefonos;
    private javax.swing.JTextField jtf_ubiacion;
    // End of variables declaration//GEN-END:variables
}
